# Generated by Django 3.2.8 on 2021-10-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_auto_20211021_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaapp',
            name='size',
            field=models.CharField(choices=[('Small', 'küçük'), ('Medium', 'orta'), ('Large', 'büyük')], max_length=50),
        ),
    ]
