# Generated by Django 3.2.8 on 2021-10-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_alter_pizzaapp_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaapp',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=50),
        ),
    ]
